import { DateTime } from 'luxon';

import {
  formatAddressLine,
  formatDate,
  getApplicantOrPetitionerAnumber,
  getReceiptNumberWithAnumber,
  primaryAddress,
  primaryApplicant,
} from './lexical/letterEditor/nodeDomSerializers/DraftSerializerUtil';
import { getCalculatedLetterDateFromDraft } from '../../../../components/dateHelpers';

export const VARIABLE_START = '[[[';
export const VARIABLE_END = ']]]';

// The Variable Constants must match what is in the database. ** Keep in Alphabetical order
export const ASSOCIATED_RECEIPT_NUMBER_VARIABLE = 'LETTER_ASSOCIATED_RECEIPT_NBR';
export const ALIEN_NUMBER_VARIABLE = 'A_NUMBER';
export const ANUMBER_BARCODE_VARIABLE = 'A_NUMBER_BARCODE';
export const CURRENT_DATE_VARIABLE = 'CURRENTDATE';
export const CREATE_USER_NAME_TX_VARIABLE = 'CREATE_USER_NAME_TX';
export const CREATE_USER_RP_CD_VARIABLE = 'CREATE_USER_RP_CD';
export const DHS_SEAL_VARIABLE = 'DHS_SEAL';
export const FORM_TYPE_NAME_VARIABLE = 'FORM_TYPE_NAME_TX';
export const LETTER_DATE_VARIABLE = 'LETTER_DATE';
export const LETTER_APPEALED_FORM_VARIABLE = 'LETTER_APPEALED_FORM_TYPE_CD';
export const LETTER_LAST_DECISION_DATE_VARIABLE = 'LETTER_LAST_DECISION_DT';
export const LETTER_RECEIPT_DATE_VARIABLE = 'LETTER_CASE_RECEIPT_DT';
export const LETTER_RECEIPT_NUMBER_VARIABLE = 'LETTER_RECEIPT_NBR';
export const LETTERHEADER_ADDRESS_BLOCK_VARIABLE = 'LETTERHEADER_ADDRESS_BLOCK';
export const LETTERHEADER_CIS_SEAL_VARIABLE = 'LETTERHEADER_CIS_SEAL';
export const LETTERHEADER_LETTER_DATE_VARIABLE = 'LETTERHEADER_LETTER_DATE';
export const LETTERHEADER_RECEIPT_ANUMBER_VARIABLE = 'LETTERHEADER_RECEIPT_NUMBER_WITH_ANUMBER';
export const PAGEBREAK_VARIABLE = 'PAGEBREAK';
export const ORGANIZATION_ADDRESS_VARIABLE = 'ORGANIZATION_ADDRESS';
export const ORGANIZATION_NAME_VARIABLE = 'ORGANIZATION_NAME';
export const RPCODE_VARIABLE = 'RPCODE';

// Petitioner
export const PETITIONER_A_NUMBER_VARIABLE = 'LETTER_PETITIONER_A_NBR';
export const PETITIONER_CITY_VARIABLE = 'LETTER_PETITIONER_CITY_TX';
export const PETITIONER_DOB_VARIABLE = 'LETTER_PETITIONER_BIRTH_DT';
export const PETITIONER_FIRM_NAME_VARIABLE = 'LETTER_PETITIONER_FIRM_NAME_TX';
export const PETITIONER_FIRST_NAME_VARIABLE = 'LETTER_PETITIONER_FIRST_NAME_TX';
export const PETITIONER_IN_CARE_OF_VARIABLE = 'LETTER_PETITIONER_IN_CARE_OF_TX';
export const PETITIONER_LAST_NAME_VARIABLE = 'LETTER_PETITIONER_LAST_NAME_TX';
export const PETITIONER_MIDDLE_NAME_VARIABLE = 'LETTER_PETITIONER_MIDDLE_NAME_TX';
export const PETITIONER_STATE_VARIABLE = 'LETTER_PETITIONER_STATE_TX';
export const PETITIONER_STREET_VARIABLE = 'LETTER_PETITIONER_STREET_TX';
export const PETITIONER_ZIP_CODE_VARIABLE = 'LETTER_PETITIONER_ZIP_CD';

// Primary Applicant
export const PRIMARY_APPLICANT_A_NUMBER_VARIABLE = 'LETTER_BENEFICIARY_A_NBR';
export const PRIMARY_APPLICANT_CITY_VARIABLE = 'LETTER_BENEFICIARY_CITY_TX';
export const PRIMARY_APPLICANT_DOB_VARIABLE = 'LETTER_BENEFICIARY_BIRTH_DT';
export const PRIMARY_APPLICANT_FIRST_NAME_VARIABLE = 'LETTER_BENEFICIARY_FIRST_NAME_TX';
export const PRIMARY_APPLICANT_LAST_NAME_VARIABLE = 'LETTER_BENEFICIARY_LAST_NAME_TX';
export const PRIMARY_APPLICANT_MIDDLE_NAME_VARIABLE = 'LETTER_BENEFICIARY_MIDDLE_NAME_TX';
export const PRIMARY_APPLICANT_STATE_VARIABLE = 'LETTER_BENEFICIARY_STATE_TX';
export const PRIMARY_APPLICANT_STREET_VARIABLE = 'LETTER_BENEFICIARY_STREET_TX';
export const PRIMARY_APPLICANT_SUITE_APT_VARIABLE = 'LETTER_BENEFICIARY_SUITE_APT_TX';
export const PRIMARY_APPLICANT_ZIP_VARIABLE = 'LETTER_BENEFICIARY_ZIP_CD';

export const RECEIPT_NUMBER_BARCODE_VARIABLE = 'RECEIPT_NUMBER_BARCODE';
export const RECEIPT_NUMBER_VARIABLE = 'RECEIPT_NUMBER';
export const RECIPIENT_ADDRESS_VARIABLE = 'RECIPIENT_ADDRESS';

// Representative Variables
export const REPRESENTATIVE_CITY_VARIABLE = 'LETTER_REPRESENTATIVE_CITY_TX';
export const REPRESENTATIVE_COUNTRY_VARIABLE = 'LETTER_REPRESENTATIVE_COUNTRY_TX';
export const REPRESENTATIVE_FIRM_NAME_VARIABLE = 'LETTER_REPRESENTATIVE_FIRM_NAME_TX';
export const REPRESENTATIVE_FIRST_NAME_VARIABLE = 'LETTER_REPRESENTATIVE_FIRST_NAME_TX';
export const REPRESENTATIVE_IN_CARE_OF_VARIABLE = 'LETTER_REPRESENTATIVE_IN_CARE_OF_TX';
export const REPRESENTATIVE_LAST_NAME_VARIABLE = 'LETTER_REPRESENTATIVE_LAST_NAME_TX';
export const REPRESENTATIVE_MIDDLE_NAME_VARIABLE = 'LETTER_REPRESENTATIVE_MIDDLE_NAME_TX';
export const REPRESENTATIVE_POSTAL_CODE_VARIABLE = 'LETTER_REPRESENTATIVE_POSTAL_CD';
export const REPRESENTATIVE_PROVINCE_VARIABLE = 'LETTER_REPRESENTATIVE_PROVINCE_TX';
export const REPRESENTATIVE_STATE_VARIABLE = 'LETTER_REPRESENTATIVE_STATE_TX';
export const REPRESENTATIVE_STREET1_VARIABLE = 'LETTER_REPRESENTATIVE_STREET_1_TX';
export const REPRESENTATIVE_STREET2_VARIABLE = 'LETTER_REPRESENTATIVE_STREET_2_TX';
export const REPRESENTATIVE_ZIP_CODE_VARIABLE = 'LETTER_REPRESENTATIVE_ZIP_CD';

// Search Text variables are needed for the variable conversion process  ** Keep in Alphabetical order
export const ALIEN_NUMBER_BARCODE_SEARCH_TEXT = `${VARIABLE_START}${ANUMBER_BARCODE_VARIABLE}${VARIABLE_END}`;
export const ASSOCIATED_RECEIPT_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${ASSOCIATED_RECEIPT_NUMBER_VARIABLE}${VARIABLE_END}`;
export const ALIEN_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${ALIEN_NUMBER_VARIABLE}${VARIABLE_END}`;
export const CREATE_USER_NAME_SEARCH_TEXT = `${VARIABLE_START}${CREATE_USER_NAME_TX_VARIABLE}${VARIABLE_END}`;
export const CREATE_USER_RP_CD_SEARCH_TEXT = `${VARIABLE_START}${CREATE_USER_RP_CD_VARIABLE}${VARIABLE_END}`;
export const CURRENT_DATE_SEARCH_TEXT = `${VARIABLE_START}${CURRENT_DATE_VARIABLE}${VARIABLE_END}`;
export const DHS_SEAL_SEARCH_TEXT = `${VARIABLE_START}${DHS_SEAL_VARIABLE}${VARIABLE_END}`;
export const FORM_TYPE_NAME_SEARCH_TEXT = `${VARIABLE_START}${FORM_TYPE_NAME_VARIABLE}${VARIABLE_END}`;
export const LETTER_APPEALED_FORM_SEARCH_TEXT = `${VARIABLE_START}${LETTER_APPEALED_FORM_VARIABLE}${VARIABLE_END}`;
export const LETTER_DATE_SEARCH_TEXT = `${VARIABLE_START}${LETTER_DATE_VARIABLE}${VARIABLE_END}`;
export const LETTER_LAST_DECISION_DATE_SEARCH_TEXT = `${VARIABLE_START}${LETTER_LAST_DECISION_DATE_VARIABLE}${VARIABLE_END}`;
export const LETTER_RECEIPT_DATE_SEARCH_TEXT = `${VARIABLE_START}${LETTER_RECEIPT_DATE_VARIABLE}${VARIABLE_END}`;
export const LETTER_RECEIPT_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${LETTER_RECEIPT_NUMBER_VARIABLE}${VARIABLE_END}`;
export const LETTERHEADER_LETTER_DATE_SEARCH_TEXT = `${VARIABLE_START}${LETTERHEADER_LETTER_DATE_VARIABLE}${VARIABLE_END}`;

export const LETTERHEADER_ADDRESS_BLOCK_SEARCH_TEXT = `${VARIABLE_START}${LETTERHEADER_ADDRESS_BLOCK_VARIABLE}${VARIABLE_END}`;
export const LETTERHEADER_CIS_SEAL_SEARCH_TEXT = `${VARIABLE_START}${LETTERHEADER_CIS_SEAL_VARIABLE}${VARIABLE_END}`;
export const LETTERHEADER_RECEIPT_ANUMBER_SEARCH_TEXT = `${VARIABLE_START}${LETTERHEADER_RECEIPT_ANUMBER_VARIABLE}${VARIABLE_END}`;
export const ORGANIZATION_ADDRESS_SEARCH_TEXT = `${VARIABLE_START}${ORGANIZATION_ADDRESS_VARIABLE}${VARIABLE_END}`;
export const ORGANIZATION_NAME_SEARCH_TEXT = `${VARIABLE_START}${ORGANIZATION_NAME_VARIABLE}${VARIABLE_END}`;
export const PAGEBREAK_SEARCH_TEXT = `${VARIABLE_START}${PAGEBREAK_VARIABLE}${VARIABLE_END}`;
export const RPCODE_SEARCH_TEXT = `${VARIABLE_START}${RPCODE_VARIABLE}${VARIABLE_END}`;

// Petitoner Search Text
export const PETITIONER_A_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_A_NUMBER_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_CITY_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_CITY_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_DOB_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_DOB_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_FIRM_NAME_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_FIRM_NAME_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_FIRST_NAME_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_FIRST_NAME_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_IN_CARE_OF_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_IN_CARE_OF_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_LAST_NAME_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_LAST_NAME_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_MIDDLE_NAME_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_MIDDLE_NAME_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_STATE_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_STATE_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_STREET_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_STREET_VARIABLE}${VARIABLE_END}`;
export const PETITIONER_ZIP_CODE_SEARCH_TEXT = `${VARIABLE_START}${PETITIONER_ZIP_CODE_VARIABLE}${VARIABLE_END}`;

// Primary Applicant
export const PRIMARY_APPLICANT_A_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_A_NUMBER_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_CITY_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_CITY_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_DOB_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_DOB_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_FIRST_NAME_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_FIRST_NAME_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_LAST_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_LAST_NAME_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_MIDDLE_NAME_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_MIDDLE_NAME_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_STATE_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_STATE_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_STREET_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_STREET_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_SUITE_APT_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_SUITE_APT_VARIABLE}${VARIABLE_END}`;
export const PRIMARY_APPLICANT_ZIP_SEARCH_TEXT = `${VARIABLE_START}${PRIMARY_APPLICANT_ZIP_VARIABLE}${VARIABLE_END}`;

export const RECEIPT_NUMBER_BARCODE_SEARCH_TEXT = `${VARIABLE_START}${RECEIPT_NUMBER_BARCODE_VARIABLE}${VARIABLE_END}`;
export const RECEIPT_NUMBER_SEARCH_TEXT = `${VARIABLE_START}${RECEIPT_NUMBER_VARIABLE}${VARIABLE_END}`;
export const RECIPIENT_ADDRESS_SEARCH_TEXT = `${VARIABLE_START}${RECIPIENT_ADDRESS_VARIABLE}${VARIABLE_END}`;

// Representative Search Text
export const REPRESENTATIVE_CITY_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_CITY_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_COUNTRY_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_COUNTRY_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_FIRM_NAME_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_FIRM_NAME_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_FIRST_NAME_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_FIRST_NAME_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_IN_CARE_OF_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_IN_CARE_OF_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_LAST_NAME_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_LAST_NAME_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_MIDDLE_NAME_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_MIDDLE_NAME_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_POSTAL_CODE_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_POSTAL_CODE_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_PROVINCE_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_PROVINCE_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_STATE_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_STATE_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_STREET1_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_STREET1_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_STREET2_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_STREET2_VARIABLE}${VARIABLE_END}`;
export const REPRESENTATIVE_ZIP_CODE_SEARCH_TEXT = `${VARIABLE_START}${REPRESENTATIVE_ZIP_CODE_VARIABLE}${VARIABLE_END}`;

// ** NOTE: This method is currently used by both the variable conversion process and the Add Variable Content Modal.
// if the value returned from the map needs to be different (ex: formatting), we will need a separate method or map.
// currently they are in sync so, what is shown on the modal is what gets shown in the editor
export const getVariableValue = (variableName, draft, userData) => {
  const variableNameUpper = variableName?.toUpperCase();
  const organizationAddress = draft?.organization?.organizationAddressXrefs?.find((org) => org.default === true);

  const draftVariableMap = {
    [ALIEN_NUMBER_VARIABLE]: () => getApplicantOrPetitionerAnumber(draft),
    [ASSOCIATED_RECEIPT_NUMBER_VARIABLE]: () => draft?.registration?.associatedReceiptNumber,
    [CREATE_USER_NAME_TX_VARIABLE]: () =>
      draft?.creator ? `${draft.creator.firstName ?? ''}${draft.creator.lastName ? ` ${draft.creator.lastName}` : ''}` : '',
    [CREATE_USER_RP_CD_VARIABLE]: () => draft?.creator?.rpcode,
    [CURRENT_DATE_VARIABLE]: () => DateTime.now().toFormat('MMMM dd, yyyy'),
    [FORM_TYPE_NAME_VARIABLE]: () => draft?.registration?.formTypeName,
    [LETTER_APPEALED_FORM_VARIABLE]: () => draft?.registration?.appealedFormTypeCode,
    [LETTER_DATE_VARIABLE]: () => getCalculatedLetterDateFromDraft(draft),
    [LETTER_LAST_DECISION_DATE_VARIABLE]: () => formatDate(draft?.lastDecisionDate),
    [LETTER_RECEIPT_DATE_VARIABLE]: () => formatDate(draft?.registration?.receiptDate),
    [LETTER_RECEIPT_NUMBER_VARIABLE]: () => draft?.registration?.receiptNumber,
    [LETTERHEADER_LETTER_DATE_VARIABLE]: () => getCalculatedLetterDateFromDraft(draft),
    [LETTERHEADER_RECEIPT_ANUMBER_VARIABLE]: () => getReceiptNumberWithAnumber(draft),
    [ORGANIZATION_ADDRESS_VARIABLE]: () => formatAddressLine(organizationAddress?.address),
    [ORGANIZATION_NAME_VARIABLE]: () => draft?.organization?.name,
    [PETITIONER_A_NUMBER_VARIABLE]: () => draft?.petitionerType?.aNumber,
    [PETITIONER_CITY_VARIABLE]: () => draft?.petitionerType?.address?.city,
    [PETITIONER_DOB_VARIABLE]: () => formatDate(draft?.petitionerType?.dateOfBirth),
    [PETITIONER_FIRM_NAME_VARIABLE]: () => draft?.petitionerType?.firmName,
    [PETITIONER_FIRST_NAME_VARIABLE]: () => draft?.petitionerType?.firstName,
    [PETITIONER_IN_CARE_OF_VARIABLE]: () => draft?.petitionerType?.inCareOf,
    [PETITIONER_LAST_NAME_VARIABLE]: () => draft?.petitionerType?.lastName,
    [PETITIONER_MIDDLE_NAME_VARIABLE]: () => draft?.petitionerType?.middleName,
    [PETITIONER_STATE_VARIABLE]: () => draft?.petitionerType?.address?.state?.code, // code: VA, name: Virginia
    [PETITIONER_STREET_VARIABLE]: () => draft?.petitionerType?.address?.street,
    [PETITIONER_ZIP_CODE_VARIABLE]: () => draft?.petitionerType?.address?.zipCode,
    [PRIMARY_APPLICANT_A_NUMBER_VARIABLE]: () => primaryApplicant(draft)?.aNumber,
    [PRIMARY_APPLICANT_CITY_VARIABLE]: () => primaryApplicant(draft)?.address?.city,
    [PRIMARY_APPLICANT_DOB_VARIABLE]: () => formatDate(primaryApplicant(draft)?.dateOfBirth),
    [PRIMARY_APPLICANT_FIRST_NAME_VARIABLE]: () => primaryApplicant(draft)?.firstName,
    [PRIMARY_APPLICANT_LAST_NAME_VARIABLE]: () => primaryApplicant(draft)?.lastName,
    [PRIMARY_APPLICANT_MIDDLE_NAME_VARIABLE]: () => primaryApplicant(draft)?.middleName,
    [PRIMARY_APPLICANT_STATE_VARIABLE]: () => primaryApplicant(draft)?.address?.state?.code, // code: VA, name: Virginia
    [PRIMARY_APPLICANT_STREET_VARIABLE]: () => primaryApplicant(draft)?.address?.street,
    [PRIMARY_APPLICANT_SUITE_APT_VARIABLE]: () => primaryApplicant(draft)?.address?.aptSuiteFloor,
    [PRIMARY_APPLICANT_ZIP_VARIABLE]: () => primaryApplicant(draft)?.address?.zipCode,
    [RECEIPT_NUMBER_VARIABLE]: () => draft?.registration?.receiptNumber,
    [RECIPIENT_ADDRESS_VARIABLE]: () => formatAddressLine(primaryAddress(draft)),
    [REPRESENTATIVE_CITY_VARIABLE]: () => draft?.representativeType?.address?.city,
    [REPRESENTATIVE_COUNTRY_VARIABLE]: () => draft?.representativeType?.address?.country?.description,
    [REPRESENTATIVE_FIRM_NAME_VARIABLE]: () => draft?.representativeType?.firmName,
    [REPRESENTATIVE_FIRST_NAME_VARIABLE]: () => draft?.representativeType?.firstName,
    [REPRESENTATIVE_IN_CARE_OF_VARIABLE]: () => draft?.representativeType?.inCareOf,
    [REPRESENTATIVE_LAST_NAME_VARIABLE]: () => draft?.representativeType?.lastName,
    [REPRESENTATIVE_MIDDLE_NAME_VARIABLE]: () => draft?.representativeType?.middleName,
    [REPRESENTATIVE_POSTAL_CODE_VARIABLE]: () => draft?.representativeType?.address?.postalCode,
    [REPRESENTATIVE_PROVINCE_VARIABLE]: () => draft?.representativeType?.address?.province,
    [REPRESENTATIVE_STATE_VARIABLE]: () => draft?.representativeType?.address?.state?.code, // code: VA, name: Virginia
    [REPRESENTATIVE_STREET1_VARIABLE]: () => draft?.representativeType?.address?.street,
    [REPRESENTATIVE_STREET2_VARIABLE]: () => draft?.representativeType?.address?.aptSuiteFloor,
    [REPRESENTATIVE_ZIP_CODE_VARIABLE]: () => draft?.representativeType?.address?.zipCode,
    [RPCODE_VARIABLE]: () => userData?.rpcode,
  };
  return draftVariableMap[variableNameUpper] ? draftVariableMap[variableNameUpper]() : undefined;
};

export const removeBracketsFromSearchText = (searchText) => {
  if (searchText?.startsWith(VARIABLE_START) && searchText?.endsWith(VARIABLE_END)) {
    return searchText?.slice(VARIABLE_START.length, -VARIABLE_END.length);
  }
  return searchText;
};

// TEMP FIX - Variables will be removed from DB or flagged with active/inactive column
export const inactiveVariables = [RECIPIENT_ADDRESS_VARIABLE, DHS_SEAL_VARIABLE];
